[build-system]
requires = ["setuptools>=69.5.1", "wheel>=0.42.0"]
build-backend = "setuptools.build_meta"

[project]
name = "waseok-chatbot"
version = "1.0.0"
description = "와석초 카카오톡 챗봇"
requires-python = ">=3.11" 