[build-system]
requires = ["setuptools>=68.0.0", "wheel>=0.41.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wasuk-elementary-chatbot"
version = "1.0.0"
description = "와석초등학교 AI 챗봇"
requires-python = ">=3.13" 